version: "3.2"
services:
    zosConnect:
        image: icr.io/zosconnect/ibm-zcon-designer:3.0.98
        user: root
        environment:
            - CICS_USER=IBMUSER
            - CICS_PASSWORD={aes}ARAdLDaOsYUcWsXQlMt7PxngB3/Vuk6niPORk/1K42ZBqrS3S7CnA6lgYWR/ue+G3qhbkjbIpq+3mc9f009lL77cVQ6sf5zmjOyx/dxUPPEl/a/FEsinlrr3XoT3UMkvafDsWDM1N5Ff
            - CICS_HOST=192.168.1.171.nip.io
            - CICS_PORT=12080
            - DB2_USERNAME=IBMUSER
            - DB2_PASSWORD={aes}ARAdLDaOsYUcWsXQlMt7PxngB3/Vuk6niPORk/1K42ZBqrS3S7CnA6lgYWR/ue+G3qhbkjbIpq+3mc9f009lL77cVQ6sf5zmjOyx/dxUPPEl/a/FEsinlrr3XoT3UMkvafDsWDM1N5Ff
            - DB2_HOST=192.168.1.171.nip.io
            - DB2_PORT=5045
            - HTTP_PORT=9080
            - zosconnect_remote_download_allowlist=BLOCK_ALL
        ports:
            - "9443:9443"
            - "9080:9080"
        volumes:
            - ./CatalogManagerApi:/workspace/project
            - ./logs/:/logs/
            - ./certs:/config/resources/security/:ro